name: brendan.solorz
favicon: null
layout_spectrum: 0.88377
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#716f70'
    - '#4e4946'
    - '#aeaeae'
    - '#90993f'
  brandStrength: 0.8125
  lightness: 0.8756526904180646
  saturation: 0.7309828496072441
  rhythmicContrast: 0.3007989937905222
purpose: []
